### ISSUE TITLE
Include code for fetching updated map from upstream

### ISSUE THREAD

**Issue by willscott** [libp2p/go-libp2p-asn-util#11]
This package needs to be periodically updated as new assignments occur if it's to be used.

@aschmahmann - do you know where `generate/ipv6_asn.asset.tsv` came from and how we can provide code for getting new versions of that source file?

**Comment by aschmahmann** [comment]
@aarshkshah1992 would know best here, but I think its from the website linked to from the README https://iptoasn.com/

**Comment by aarshkshah1992** [comment]
@aschmahmann is correct.

**Comment by willscott** [comment]
that site indicates it's deprecated and will go away, and doesn't include a methodology for how the database is generated (the source code linked runs the website to provide an API over the database, but doesn't give information on how to update or regenerate the database itself). What's our plan as it falls out of date?

**Comment by aarshkshah1992** [comment]
@willscott When we did this, the goal was to get it working for immediate DHT resilience against attacks. I couldn't find any free & open source reliable dataset that's updated regularly when I was working on this. 

The best I could find was https://lite.ip2location.com/ but IIRC, there were some licensing concerns around using that.

So yeah, this is as an yet unsolved problem.

**Comment by willscott** [comment]
a reasonable authoritative upstream is http://archive.routeviews.org/dnszones/

It's gonna be hard to notice how far out of date this thing gets, so at some point we're gonna need to queue up someone spending a week to get this into shape. @aschmahmann i guess you're maybe the right person to try and track this for prioritization?
